apiVersion: v1
kind: Pod
metadata:
        name: phpmyadmin
        labels:
                app: phpmyadmin
spec:
        containers:
        - name: server
          imagePullPolicy: Never
          image : phpmyadmin:latest
          ports:
          - name: https
            containerPort: 5000
            protocol: TCP
