apiVersion: v1
kind: Service
metadata:
  name: service-phpmyadmin
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 5000
      targetPort: 5000
