apiVersion: v1
kind: Pod
metadata:
        name: wordpress
        labels:
                app: wordpress
spec:
        containers:
        - name: server
          imagePullPolicy: Never
          image : wordpress:latest
          ports:
          - name: https
            containerPort: 5050
            protocol: TCP
