apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
    labels:
        app: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              imagePullPolicy: Never
              image: nginx:latest
              ports:
              - containerPort: 80
              - containerPort: 443
              livenessProbe:
                  httpGet:
                    path: ./
                    port: 443
                    scheme: HTTPS
                  initialDelaySeconds: 30
                  periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
